### ISSUE TITLE
problem to get serp when setting page number

### ISSUE THREAD

**Issue by yumekana** [serp-scrape/serps#30]
hi, I got a problem to get serp when I set page number.
It just returns empty space to the "start" parameter.

I found that QueryParam class 's queryItemToString method returns only name when the value is number type.

Thank you for great library anyway !

shinjiro nojima

**Comment by gsouf** [comment]
Hi @yumekana 

Thanks for your interest in serps!

Are you using version 0.1 of the library? 

Indedd  it seems that there is an issue with the method ``queryItemToString`` but it only exists in the master branch for next version of the library (0.2) and if you are using version 0.1 the bug is probably from an other source.

**Comment by yumekana** [comment]
Hi, 

Oh yes, the branch I tried was master because I wanted to parse mobile serp. sorry, I should mention about that!

**Comment by gsouf** [comment]
Ok we are all right, would you like to send a PR ?

**Comment by yumekana** [comment]
hi, thanks.
currently i do composer require from your repository directory. i do not know how to post PR in this case...
later, I will fork serp-spider then create PR from next issue if I will find!

**Comment by gsouf** [comment]
@yumekana can you try again please

**Comment by lifestyle-design** [comment]
hi, gsouf
I tested and works just fine thanks !
