### ISSUE TITLE
First configuration

### ISSUE THREAD

**Issue by MrZANO** [serp-scrape/serps#34]
Sorry but I can not understand how to run the first installation. I installed and configured Symfony, then I entered all the configuration files in composer and ran a composer update. What should I do next?

Thanks

**Comment by gsouf** [comment]
Hi @MrZANO 

You can find further instructions for google right there: https://serp-spider.github.io/documentation/search-engine/google/

If you need further help, I invite you to chat on gitter because we try to keep github for bugs and features management only. You will find a button to access it at the bottom right hand corner of the website.
Thanks
